# Generated by Django 6.0.5 on 2026-06-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("inscriptos", models.IntegerField()),
                ("profesor", models.CharField(default="Norman", max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
