# Generated by Django 6.0.5 on 2026-06-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                (
                    "especialidad",
                    models.IntegerField(
                        choices=[
                            (1, "Python"),
                            (2, "Data Analitycs"),
                            (3, "Data Science"),
                            (4, "IA Prompts"),
                            (5, "IA Agentes"),
                        ]
                    ),
                ),
            ],
        ),
    ]
