# Generated by Django 6.0.5 on 2026-06-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0002_profesor"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="email",
            field=models.EmailField(default="a@b.com", max_length=254),
            preserve_default=False,
        ),
    ]
